# Generated by Django 5.0.2 on 2024-08-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(default='1', related_name='news', to='news.category'),
        ),
    ]
